package net.minecraft.client.renderer.entity.model;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Iterables;
import com.google.common.collect.Lists;
import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.platform.GlStateManager;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import dimasik.Load;
import dimasik.modules.render.CustomModel;
import java.util.List;
import java.util.Random;
import net.minecraft.client.Minecraft;
import net.minecraft.client.entity.player.ClientPlayerEntity;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.model.BipedModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.LivingEntity;
import net.minecraft.util.HandSide;

public class PlayerModel<T extends LivingEntity>
extends BipedModel<T> {
    private List<ModelRenderer> modelRenderers = Lists.newArrayList();
    public final ModelRenderer bipedLeftArmwear;
    public final ModelRenderer bipedRightArmwear;
    public final ModelRenderer bipedLeftLegwear;
    public final ModelRenderer bipedRightLegwear;
    public final ModelRenderer bipedBodyWear;
    private final ModelRenderer bipedCape;
    private final ModelRenderer bipedDeadmau5Head;
    private final boolean smallArms;
    public final ModelRenderer rabbitBone;
    public final ModelRenderer rabbitHead;
    public final ModelRenderer rabbitLarm;
    public final ModelRenderer rabbitRarm;
    public final ModelRenderer rabbitLleg;
    public final ModelRenderer rabbitRleg;
    private final ModelRenderer RightLeg;
    private final ModelRenderer LeftLeg;
    private final ModelRenderer Body;
    private final ModelRenderer RightArm;
    private final ModelRenderer Head;
    private final ModelRenderer LeftArm;
    ModelRenderer Back;
    ModelRenderer Nose;
    ModelRenderer RightEar;
    ModelRenderer RightWhiskers;
    ModelRenderer LeftEar;
    ModelRenderer UpperTail;
    ModelRenderer chinBody;
    ModelRenderer RightEye;
    ModelRenderer LowerTail;
    ModelRenderer RightRearFoot;
    ModelRenderer LeftRearFoot;
    ModelRenderer RightFrontLeg;
    ModelRenderer RightFrontFoot;
    ModelRenderer LeftFrontLeg;
    ModelRenderer LeftFrontFoot;
    ModelRenderer Chin;
    ModelRenderer LeftWhiskers;
    ModelRenderer chinHead;
    ModelRenderer LeftEye;
    private final ModelRenderer head7;
    private final ModelRenderer left_horn;
    private final ModelRenderer right_horn;
    private final ModelRenderer body7;
    private final ModelRenderer left_wing;
    private final ModelRenderer right_wing;
    private final ModelRenderer left_arm7;
    private final ModelRenderer right_arm7;
    private final ModelRenderer left_leg7;
    private final ModelRenderer left_leg1;
    public ModelRenderer fredbody;
    private final ModelRenderer bone2;
    public ModelRenderer armRight;
    public ModelRenderer hat2;
    public ModelRenderer hat;
    private final ModelRenderer bone3;
    public ModelRenderer crotch;
    private final ModelRenderer bone7;
    private final ModelRenderer right_leg7;
    public ModelRenderer legLeft;
    private final ModelRenderer right_leg3;
    public ModelRenderer footLeft;
    public ModelRenderer earLeft;
    public ModelRenderer earRightpad_1;
    private final ModelRenderer bone4;
    public ModelRenderer legRight;
    private final ModelRenderer bone5;
    private final ModelRenderer bone6;
    public ModelRenderer torso;
    public ModelRenderer armRightpad;
    public ModelRenderer armRight2;
    public ModelRenderer handRight;
    public ModelRenderer legRightpad2;
    public ModelRenderer legRight2;
    public ModelRenderer handLeft;
    public ModelRenderer earRightpad;
    public ModelRenderer armRightpad2;
    public ModelRenderer legRightpad;
    public ModelRenderer armLeft;
    public ModelRenderer fredhead;
    public ModelRenderer legLeft2;
    public ModelRenderer legLeftpad2;
    public ModelRenderer armLeftpad2;
    public ModelRenderer armLeftpad;
    public ModelRenderer armLeft2;
    public ModelRenderer frednose;
    public ModelRenderer earRight;
    public ModelRenderer footRight;
    public ModelRenderer legLeftpad;
    public ModelRenderer jaw;
    private T currentEntity;

    public PlayerModel(float modelSize, boolean smallArmsIn) {
        super(RenderType::getEntityTranslucent, modelSize, 0.0f, 64, 64);
        this.smallArms = smallArmsIn;
        this.bipedDeadmau5Head = new ModelRenderer(this, 24, 0);
        this.bipedDeadmau5Head.addBox(-3.0f, -6.0f, -1.0f, 6.0f, 6.0f, 1.0f, modelSize);
        this.bipedCape = new ModelRenderer(this, 0, 0);
        this.bipedCape.setTextureSize(64, 32);
        this.bipedCape.addBox(-5.0f, 0.0f, -1.0f, 10.0f, 16.0f, 1.0f, modelSize);
        if (smallArmsIn) {
            this.bipedLeftArm = new ModelRenderer(this, 32, 48);
            this.bipedLeftArm.addBox(-1.0f, -2.0f, -2.0f, 3.0f, 12.0f, 4.0f, modelSize);
            this.bipedLeftArm.setRotationPoint(5.0f, 2.5f, 0.0f);
            this.bipedRightArm = new ModelRenderer(this, 40, 16);
            this.bipedRightArm.addBox(-2.0f, -2.0f, -2.0f, 3.0f, 12.0f, 4.0f, modelSize);
            this.bipedRightArm.setRotationPoint(-5.0f, 2.5f, 0.0f);
            this.bipedLeftArmwear = new ModelRenderer(this, 48, 48);
            this.bipedLeftArmwear.addBox(-1.0f, -2.0f, -2.0f, 3.0f, 12.0f, 4.0f, modelSize + 0.25f);
            this.bipedLeftArmwear.setRotationPoint(5.0f, 2.5f, 0.0f);
            this.bipedRightArmwear = new ModelRenderer(this, 40, 32);
            this.bipedRightArmwear.addBox(-2.0f, -2.0f, -2.0f, 3.0f, 12.0f, 4.0f, modelSize + 0.25f);
            this.bipedRightArmwear.setRotationPoint(-5.0f, 2.5f, 10.0f);
        } else {
            this.bipedLeftArm = new ModelRenderer(this, 32, 48);
            this.bipedLeftArm.addBox(-1.0f, -2.0f, -2.0f, 4.0f, 12.0f, 4.0f, modelSize);
            this.bipedLeftArm.setRotationPoint(5.0f, 2.0f, 0.0f);
            this.bipedLeftArmwear = new ModelRenderer(this, 48, 48);
            this.bipedLeftArmwear.addBox(-1.0f, -2.0f, -2.0f, 4.0f, 12.0f, 4.0f, modelSize + 0.25f);
            this.bipedLeftArmwear.setRotationPoint(5.0f, 2.0f, 0.0f);
            this.bipedRightArmwear = new ModelRenderer(this, 40, 32);
            this.bipedRightArmwear.addBox(-3.0f, -2.0f, -2.0f, 4.0f, 12.0f, 4.0f, modelSize + 0.25f);
            this.bipedRightArmwear.setRotationPoint(-5.0f, 2.0f, 10.0f);
        }
        this.bipedLeftLeg = new ModelRenderer(this, 16, 48);
        this.bipedLeftLeg.addBox(-2.0f, 0.0f, -2.0f, 4.0f, 12.0f, 4.0f, modelSize);
        this.bipedLeftLeg.setRotationPoint(1.9f, 12.0f, 0.0f);
        this.bipedLeftLegwear = new ModelRenderer(this, 0, 48);
        this.bipedLeftLegwear.addBox(-2.0f, 0.0f, -2.0f, 4.0f, 12.0f, 4.0f, modelSize + 0.25f);
        this.bipedLeftLegwear.setRotationPoint(1.9f, 12.0f, 0.0f);
        this.bipedRightLegwear = new ModelRenderer(this, 0, 32);
        this.bipedRightLegwear.addBox(-2.0f, 0.0f, -2.0f, 4.0f, 12.0f, 4.0f, modelSize + 0.25f);
        this.bipedRightLegwear.setRotationPoint(-1.9f, 12.0f, 0.0f);
        this.bipedBodyWear = new ModelRenderer(this, 16, 32);
        this.bipedBodyWear.addBox(-4.0f, 0.0f, -2.0f, 8.0f, 12.0f, 4.0f, modelSize + 0.25f);
        this.bipedBodyWear.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.rabbitBone = new ModelRenderer(this);
        this.rabbitBone.setRotationPoint(0.0f, 24.0f, 0.0f);
        this.rabbitBone.setTextureOffset(28, 45);
        this.rabbitBone.addBox(-5.0f, -13.0f, -5.0f, 10.0f, 11.0f, 8.0f, 0.0f);
        this.rabbitRleg = new ModelRenderer(this);
        this.rabbitRleg.setRotationPoint(-3.0f, -2.0f, -1.0f);
        this.rabbitBone.addChild(this.rabbitRleg);
        this.rabbitRleg.setTextureOffset(0, 0);
        this.rabbitRleg.addBox(-2.0f, 0.0f, -2.0f, 4.0f, 2.0f, 4.0f, 0.0f);
        this.rabbitLarm = new ModelRenderer(this);
        this.rabbitLarm.setRotationPoint(5.0f, -13.0f, -1.0f);
        this.setRotationAngle(this.rabbitLarm, 0.0f, 0.0f, -0.0873f);
        this.rabbitBone.addChild(this.rabbitLarm);
        this.rabbitLarm.setTextureOffset(0, 0);
        this.rabbitLarm.addBox(0.0f, 0.0f, -2.0f, 2.0f, 8.0f, 4.0f, 0.0f);
        this.rabbitRarm = new ModelRenderer(this);
        this.rabbitRarm.setRotationPoint(-5.0f, -13.0f, -1.0f);
        this.setRotationAngle(this.rabbitRarm, 0.0f, 0.0f, 0.0873f);
        this.rabbitBone.addChild(this.rabbitRarm);
        this.rabbitRarm.setTextureOffset(0, 0);
        this.rabbitRarm.addBox(-2.0f, 0.0f, -2.0f, 2.0f, 8.0f, 4.0f, 0.0f);
        this.rabbitLleg = new ModelRenderer(this);
        this.rabbitLleg.setRotationPoint(3.0f, -2.0f, -1.0f);
        this.rabbitBone.addChild(this.rabbitLleg);
        this.rabbitLleg.setTextureOffset(0, 0);
        this.rabbitLleg.addBox(-2.0f, 0.0f, -2.0f, 4.0f, 2.0f, 4.0f, 0.0f);
        this.rabbitHead = new ModelRenderer(this);
        this.rabbitHead.setRotationPoint(0.0f, -14.0f, -1.0f);
        this.rabbitBone.addChild(this.rabbitHead);
        this.rabbitHead.setTextureOffset(0, 0);
        this.rabbitHead.addBox(-3.0f, 0.0f, -4.0f, 6.0f, 1.0f, 6.0f, 0.0f);
        this.rabbitHead.setTextureOffset(56, 0);
        this.rabbitHead.addBox(-5.0f, -9.0f, -5.0f, 2.0f, 3.0f, 2.0f, 0.0f);
        this.rabbitHead.setTextureOffset(56, 0);
        this.rabbitHead.addBox(3.0f, -9.0f, -5.0f, 2.0f, 3.0f, 2.0f, 0.0f);
        this.rabbitHead.setTextureOffset(0, 45);
        this.rabbitHead.addBox(-4.0f, -11.0f, -4.0f, 8.0f, 11.0f, 8.0f, 0.0f);
        this.rabbitHead.setTextureOffset(46, 0);
        this.rabbitHead.addBox(1.0f, -20.0f, 0.0f, 3.0f, 9.0f, 1.0f, 0.0f);
        this.rabbitHead.setTextureOffset(46, 0);
        this.rabbitHead.addBox(-4.0f, -20.0f, 0.0f, 3.0f, 9.0f, 1.0f, 0.0f);
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.Back = new ModelRenderer(this, 0, 14);
        this.Back.addBox(-3.0f, 0.3f, 3.3f, 6.0f, 6.0f, 3.0f);
        this.Back.setRotationPoint(0.0f, 18.0f, -2.0f);
        this.Back.setTextureSize(64, 32);
        this.Back.mirror = true;
        this.setRotationAngle(this.Back, 0.2443461f, 0.0f, 0.0f);
        this.Nose = new ModelRenderer(this, 46, 24);
        this.Nose.addBox(-2.0f, -3.0f, -3.0f, 4.0f, 4.0f, 2.0f);
        this.Nose.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.Nose.setTextureSize(64, 32);
        this.Nose.mirror = true;
        this.setRotationAngle(this.Nose, 0.3687912f, 0.0f, 0.0f);
        this.RightEar = new ModelRenderer(this, 48, 8);
        this.RightEar.addBox(0.5f, -6.0f, -0.6f, 1.0f, 4.0f, 3.0f);
        this.RightEar.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.RightEar.setTextureSize(64, 32);
        this.RightEar.mirror = true;
        this.setRotationAngle(this.RightEar, 0.8726646f, 2.094395f, 0.0f);
        this.RightWhiskers = new ModelRenderer(this, 18, 19);
        this.RightWhiskers.addBox(-5.0f, -1.4f, -4.04f, 4.0f, 3.0f, 1.0f);
        this.RightWhiskers.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.RightWhiskers.setTextureSize(64, 32);
        this.RightWhiskers.mirror = true;
        this.setRotationAngle(this.RightWhiskers, -0.0872665f, 0.1745329f, 0.0f);
        this.LeftEar = new ModelRenderer(this, 48, 0);
        this.LeftEar.addBox(0.5f, -6.0f, -2.4f, 1.0f, 4.0f, 3.0f);
        this.LeftEar.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.LeftEar.setTextureSize(64, 32);
        this.LeftEar.mirror = true;
        this.setRotationAngle(this.LeftEar, -0.8726646f, 1.047198f, 0.0f);
        this.UpperTail = new ModelRenderer(this, 14, 23);
        this.UpperTail.addBox(-1.5f, 1.5f, 2.6f, 3.0f, 3.0f, 4.0f);
        this.UpperTail.setRotationPoint(0.0f, 22.2f, 4.066667f);
        this.UpperTail.setTextureSize(64, 32);
        this.UpperTail.mirror = true;
        this.setRotationAngle(this.UpperTail, 0.7330383f, 0.0f, 0.0f);
        this.chinBody = new ModelRenderer(this, 0, 0);
        this.chinBody.addBox(-3.5f, -2.0f, -1.0f, 7.0f, 7.0f, 7.0f);
        this.chinBody.setRotationPoint(0.0f, 18.0f, -2.0f);
        this.chinBody.setTextureSize(64, 32);
        this.chinBody.mirror = true;
        this.setRotationAngle(this.chinBody, -0.0872665f, 0.0f, 0.0f);
        this.LowerTail = new ModelRenderer(this, 0, 23);
        this.LowerTail.addBox(-1.0f, -1.0f, 0.0f, 2.0f, 2.0f, 5.0f);
        this.LowerTail.setRotationPoint(0.0f, 22.2f, 4.066667f);
        this.LowerTail.setTextureSize(64, 32);
        this.LowerTail.mirror = true;
        this.setRotationAngle(this.LowerTail, -0.1047198f, 0.0f, 0.0f);
        this.RightRearFoot = new ModelRenderer(this, 28, 9);
        this.RightRearFoot.addBox(-1.5f, 0.0f, -3.0f, 2.0f, 1.0f, 4.0f);
        this.RightRearFoot.setRotationPoint(-3.0f, 23.0f, 3.0f);
        this.RightRearFoot.setTextureSize(64, 32);
        this.RightRearFoot.mirror = true;
        this.setRotationAngle(this.RightRearFoot, 0.0f, 0.0698132f, 0.0f);
        this.LeftRearFoot = new ModelRenderer(this, 28, 0);
        this.LeftRearFoot.addBox(-0.5f, 0.0f, -3.0f, 2.0f, 1.0f, 4.0f);
        this.LeftRearFoot.setRotationPoint(3.0f, 23.0f, 3.0f);
        this.LeftRearFoot.setTextureSize(64, 32);
        this.LeftRearFoot.mirror = true;
        this.setRotationAngle(this.LeftRearFoot, 0.0f, -0.0698132f, 0.0f);
        this.RightFrontLeg = new ModelRenderer(this, 40, 9);
        this.RightFrontLeg.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 4.0f, 2.0f);
        this.RightFrontLeg.setRotationPoint(-3.0f, 20.0f, -3.0f);
        this.RightFrontLeg.setTextureSize(64, 32);
        this.RightFrontLeg.mirror = true;
        this.setRotationAngle(this.RightFrontLeg, -0.1858931f, 0.0f, 0.0f);
        this.RightFrontFoot = new ModelRenderer(this, 28, 14);
        this.RightFrontFoot.addBox(-1.0f, 3.0f, -2.8f, 2.0f, 1.0f, 3.0f);
        this.RightFrontFoot.setRotationPoint(-3.0f, 20.0f, -3.0f);
        this.RightFrontFoot.setTextureSize(64, 32);
        this.RightFrontFoot.mirror = true;
        this.setRotationAngle(this.RightFrontFoot, 0.0f, -0.0698132f, 0.0f);
        this.LeftFrontLeg = new ModelRenderer(this, 40, 0);
        this.LeftFrontLeg.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 4.0f, 2.0f);
        this.LeftFrontLeg.setRotationPoint(3.0f, 20.0f, -3.0f);
        this.LeftFrontLeg.setTextureSize(64, 32);
        this.LeftFrontLeg.mirror = true;
        this.setRotationAngle(this.LeftFrontLeg, -0.1858931f, 0.0f, 0.0f);
        this.LeftFrontFoot = new ModelRenderer(this, 28, 5);
        this.LeftFrontFoot.addBox(-1.0f, 3.0f, -2.8f, 2.0f, 1.0f, 3.0f);
        this.LeftFrontFoot.setRotationPoint(3.0f, 20.0f, -3.0f);
        this.LeftFrontFoot.setTextureSize(64, 32);
        this.LeftFrontFoot.mirror = true;
        this.setRotationAngle(this.LeftFrontFoot, 0.0f, 0.0698132f, 0.0f);
        this.Chin = new ModelRenderer(this, 46, 18);
        this.Chin.addBox(-2.0f, -1.3f, -4.04f, 4.0f, 3.0f, 2.0f);
        this.Chin.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.Chin.setTextureSize(64, 32);
        this.Chin.mirror = true;
        this.setRotationAngle(this.Chin, -0.1115358f, 0.0f, 0.0f);
        this.LeftWhiskers = new ModelRenderer(this, 18, 14);
        this.LeftWhiskers.addBox(1.0f, -1.4f, -4.04f, 4.0f, 3.0f, 1.0f);
        this.LeftWhiskers.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.LeftWhiskers.setTextureSize(64, 32);
        this.LeftWhiskers.mirror = true;
        this.setRotationAngle(this.LeftWhiskers, -0.0872665f, -0.1745329f, 0.0f);
        this.chinHead = new ModelRenderer(this, 28, 21);
        this.chinHead.addBox(-2.5f, -3.0f, -2.4f, 5.0f, 5.0f, 4.0f);
        this.chinHead.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.chinHead.setTextureSize(64, 32);
        this.chinHead.mirror = true;
        this.setRotationAngle(this.chinHead, 0.0f, 0.0f, 0.0f);
        this.LeftEye = new ModelRenderer(this, 0, 0);
        this.LeftEye.addBox(-2.0f, -1.8f, -3.4f, 2.0f, 2.0f, 1.0f);
        this.LeftEye.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.LeftEye.setTextureSize(64, 32);
        this.LeftEye.mirror = true;
        this.setRotationAngle(this.LeftEye, 0.0f, -1.047198f, 0.0f);
        this.RightEye = new ModelRenderer(this, 0, 3);
        this.RightEye.addBox(0.0f, -1.8f, -3.4f, 2.0f, 2.0f, 1.0f);
        this.RightEye.setRotationPoint(0.0f, 18.0f, -3.0f);
        this.RightEye.setTextureSize(64, 32);
        this.RightEye.mirror = true;
        this.setRotationAngle(this.RightEye, 0.0f, 1.047198f, 0.0f);
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.head7 = new ModelRenderer(this);
        this.head7.setRotationPoint(0.0f, -6.0f, -1.0f);
        this.head7.setTextureOffset(0, 0).addBox(-4.0f, -4.0f, -3.0f, 8.0f, 8.0f, 8.0f, 0.3f);
        this.left_horn = new ModelRenderer(this);
        this.left_horn.setRotationPoint(-8.0f, 8.0f, 0.0f);
        this.head7.addChild(this.left_horn);
        this.setRotationAngle(this.left_horn, -0.3927f, 0.3927f, -0.5236f);
        this.left_horn.setTextureOffset(32, 8).addBox(13.4346f, -5.2071f, 2.7071f, 6.0f, 2.0f, 2.0f, 0.1f);
        this.left_horn.setTextureOffset(0, 0).addBox(17.4346f, -10.4071f, 2.7071f, 2.0f, 5.0f, 2.0f, 0.1f);
        this.right_horn = new ModelRenderer(this);
        this.right_horn.setRotationPoint(8.0f, 8.0f, 0.0f);
        this.head7.addChild(this.right_horn);
        this.setRotationAngle(this.right_horn, -0.3927f, -0.3927f, 0.5236f);
        this.right_horn.setTextureOffset(32, 8).addBox(-19.4346f, -5.2071f, 2.7071f, 6.0f, 2.0f, 2.0f, 0.1f, true);
        this.right_horn.setTextureOffset(0, 0).addBox(-19.4346f, -10.4071f, 2.7071f, 2.0f, 5.0f, 2.0f, 0.1f, true);
        this.body7 = new ModelRenderer(this);
        this.body7.setRotationPoint(0.5f, -0.1f, -3.5f);
        this.setRotationAngle(this.body7, 0.1745f, 0.0f, 0.0f);
        this.body7.setTextureOffset(0, 16).addBox(-4.5f, -1.7028f, 1.4696f, 8.0f, 12.0f, 4.0f);
        this.left_wing = new ModelRenderer(this);
        this.left_wing.setRotationPoint(8.25f, -2.0f, 10.0f);
        this.body7.addChild(this.left_wing);
        this.setRotationAngle(this.left_wing, 0.0873f, -0.829f, 0.1745f);
        this.left_wing.setTextureOffset(40, 12).addBox(-7.0072f, -0.5972f, 0.7515f, 12.0f, 13.0f, 0.0f);
        this.right_wing = new ModelRenderer(this);
        this.right_wing.setRotationPoint(-9.25f, -2.0f, 10.0f);
        this.body7.addChild(this.right_wing);
        this.setRotationAngle(this.right_wing, 0.0873f, 0.829f, -0.1745f);
        this.right_wing.setTextureOffset(40, 12).addBox(-4.9928f, -0.5972f, 0.7515f, 12.0f, 13.0f, 0.0f, true);
        this.left_arm7 = new ModelRenderer(this);
        this.left_arm7.setRotationPoint(5.4f, -1.25f, -2.0f);
        this.setRotationAngle(this.left_arm7, 0.0f, 0.0f, -0.2182f);
        this.left_arm7.setTextureOffset(24, 16).addBox(-1.1f, -1.05f, 0.0f, 4.0f, 14.0f, 4.0f);
        this.right_arm7 = new ModelRenderer(this);
        this.right_arm7.setRotationPoint(-5.4f, -1.25f, -2.0f);
        this.setRotationAngle(this.right_arm7, 0.0f, 0.0f, 0.2182f);
        this.right_arm7.setTextureOffset(24, 16).addBox(-2.9f, -1.05f, 0.0f, 4.0f, 14.0f, 4.0f, true);
        this.left_leg7 = new ModelRenderer(this);
        this.left_leg7.setRotationPoint(3.0f, 10.0f, 0.0f);
        this.left_leg7.setTextureOffset(48, 22).addBox(-3.25f, -2.25f, -1.0f, 4.0f, 9.0f, 4.0f);
        this.left_leg1 = new ModelRenderer(this);
        this.left_leg1.setRotationPoint(-1.7f, -0.1f, -3.55f);
        this.left_leg7.addChild(this.left_leg1);
        this.setRotationAngle(this.left_leg1, -0.5236f, 0.0f, 0.0f);
        this.left_leg1.setTextureOffset(34, 34).addBox(0.95f, 4.6f, 8.0511f, 3.0f, 5.0f, 3.0f);
        this.bone2 = new ModelRenderer(this);
        this.bone2.setRotationPoint(1.4f, 15.0f, 0.25f);
        this.left_leg1.addChild(this.bone2);
        this.setRotationAngle(this.bone2, 0.5236f, 0.0f, 0.0f);
        this.bone2.setTextureOffset(26, 0).addBox(-0.7f, -1.15f, 9.3f, 4.0f, 2.0f, 4.0f);
        this.bone2.setTextureOffset(40, 0).addBox(-0.7f, -1.15f, 7.3f, 4.0f, 2.0f, 2.0f);
        this.bone3 = new ModelRenderer(this);
        this.bone3.setRotationPoint(-1.0f, 0.0f, -2.0f);
        this.left_leg1.addChild(this.bone3);
        this.setRotationAngle(this.bone3, 0.0f, -0.0873f, -0.2618f);
        this.bone7 = new ModelRenderer(this);
        this.bone7.setRotationPoint(1.9f, 12.0f, 0.25f);
        this.bone3.addChild(this.bone7);
        this.bone7.setTextureOffset(16, 34).addBox(-0.7911f, -10.1159f, 8.0029f, 4.0f, 4.0f, 5.0f);
        this.bone7.setTextureOffset(0, 32).addBox(-0.7911f, -15.1159f, 4.0029f, 4.0f, 9.0f, 4.0f);
        this.right_leg7 = new ModelRenderer(this);
        this.right_leg7.setRotationPoint(-3.0f, 10.0f, 0.0f);
        this.right_leg7.setTextureOffset(48, 22).addBox(-0.75f, -2.25f, -1.0f, 4.0f, 9.0f, 4.0f, true);
        this.right_leg3 = new ModelRenderer(this);
        this.right_leg3.setRotationPoint(1.7f, -0.1f, -3.55f);
        this.right_leg7.addChild(this.right_leg3);
        this.setRotationAngle(this.right_leg3, -0.5236f, 0.0f, 0.0f);
        this.right_leg3.setTextureOffset(34, 34).addBox(-3.95f, 4.6f, 8.0511f, 3.0f, 5.0f, 3.0f, true);
        this.bone4 = new ModelRenderer(this);
        this.bone4.setRotationPoint(-1.4f, 15.0f, 0.25f);
        this.right_leg3.addChild(this.bone4);
        this.setRotationAngle(this.bone4, 0.5236f, 0.0f, 0.0f);
        this.bone4.setTextureOffset(26, 0).addBox(-3.3f, -1.15f, 9.3f, 4.0f, 2.0f, 4.0f, true);
        this.bone4.setTextureOffset(40, 0).addBox(-3.3f, -1.15f, 7.3f, 4.0f, 2.0f, 2.0f, true);
        this.bone5 = new ModelRenderer(this);
        this.bone5.setRotationPoint(1.0f, 0.0f, -2.0f);
        this.right_leg3.addChild(this.bone5);
        this.setRotationAngle(this.bone5, 0.0f, 0.0873f, 0.2618f);
        this.bone6 = new ModelRenderer(this);
        this.bone6.setRotationPoint(-1.9f, 12.0f, 0.25f);
        this.bone5.addChild(this.bone6);
        this.bone6.setTextureOffset(16, 34).addBox(-3.2089f, -10.1159f, 8.0029f, 4.0f, 4.0f, 5.0f, true);
        this.bone6.setTextureOffset(0, 32).addBox(-3.2089f, -15.1159f, 4.0029f, 4.0f, 9.0f, 4.0f, true);
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.RightLeg = new ModelRenderer(this);
        this.RightLeg.setRotationPoint(-2.0f, 14.0f, 0.0f);
        this.RightLeg.setTextureOffset(0, 36).addBox(-2.0f, 0.0f, -2.0f, 4.0f, 10.0f, 4.0f, 0.0f, false);
        this.LeftLeg = new ModelRenderer(this);
        this.LeftLeg.setRotationPoint(2.0f, 14.0f, 0.0f);
        this.LeftLeg.setTextureOffset(24, 24).addBox(-2.0f, 0.0f, -2.0f, 4.0f, 10.0f, 4.0f, 0.0f, false);
        this.Body = new ModelRenderer(this);
        this.Body.setRotationPoint(0.0f, 24.0f, 0.0f);
        this.setRotationAngle(this.Body, 0.2618f, 0.0f, 0.0f);
        this.Body.setTextureOffset(0, 18).addBox(-4.0f, -23.1486f, 0.5266f, 8.0f, 14.0f, 4.0f, 0.0f, false);
        this.RightArm = new ModelRenderer(this);
        this.RightArm.setRotationPoint(-5.0f, 2.0f, 0.0f);
        this.setRotationAngle(this.RightArm, -1.57f, 0.0f, 0.0f);
        this.RightArm.setTextureOffset(36, 0).addBox(-2.0f, -2.0f, -2.0f, 3.0f, 12.0f, 3.0f, 0.0f, false);
        this.RightArm.setTextureOffset(16, 36).addBox(-1.0f, 8.0f, -4.0f, 1.0f, 2.0f, 5.0f, 0.0f, false);
        this.RightArm.setTextureOffset(31, 15).addBox(-1.0f, 8.0f, -9.0f, 1.0f, 2.0f, 5.0f, 0.0f, false);
        this.RightArm.setTextureOffset(0, 0).addBox(-1.0f, 11.0f, -7.0f, 1.0f, 1.0f, 3.0f, 0.0f, false);
        this.RightArm.setTextureOffset(24, 18).addBox(-1.0f, 10.0f, -8.0f, 1.0f, 1.0f, 5.0f, 0.0f, false);
        this.Head = new ModelRenderer(this);
        this.Head.setRotationPoint(0.0f, 1.0f, -3.0f);
        this.Head.setTextureOffset(0, 0).addBox(-5.0f, -9.75f, -5.0f, 10.0f, 10.0f, 8.0f, 0.0f, false);
        this.textureWidth = 100;
        this.textureHeight = 80;
        this.fredbody = new ModelRenderer(this, 0, 0);
        this.fredbody.setRotationPoint(0.0f, -9.0f, 0.0f);
        this.fredbody.addBox(-1.0f, -14.0f, -1.0f, 2.0f, 24.0f, 2.0f, 0.0f);
        this.torso = new ModelRenderer(this, 8, 0);
        this.torso.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.torso.addBox(-6.0f, -9.0f, -4.0f, 12.0f, 18.0f, 8.0f, 0.0f);
        this.setRotationAngle(this.torso, (float)Math.PI / 180, 0.0f, 0.0f);
        this.armRight = new ModelRenderer(this, 48, 0);
        this.armRight.setRotationPoint(-6.5f, -8.0f, 0.0f);
        this.armRight.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 10.0f, 2.0f, 0.0f);
        this.setRotationAngle(this.armRight, 0.0f, 0.0f, 0.2617994f);
        this.crotch = new ModelRenderer(this, 56, 0);
        this.crotch.setRotationPoint(0.0f, 9.5f, 0.0f);
        this.crotch.addBox(-5.5f, 0.0f, -3.5f, 11.0f, 3.0f, 7.0f, 0.0f);
        this.legRight = new ModelRenderer(this, 90, 8);
        this.legRight.setRotationPoint(-3.3f, 12.5f, 0.0f);
        this.legRight.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 10.0f, 2.0f, 0.0f);
        this.legLeft = new ModelRenderer(this, 54, 10);
        this.legLeft.setRotationPoint(3.3f, 12.5f, 0.0f);
        this.legLeft.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 10.0f, 2.0f, 0.0f);
        this.armLeft = new ModelRenderer(this, 62, 10);
        this.armLeft.setRotationPoint(6.5f, -8.0f, 0.0f);
        this.armLeft.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 10.0f, 2.0f, 0.0f);
        this.setRotationAngle(this.armLeft, 0.0f, 0.0f, -0.2617994f);
        this.fredhead = new ModelRenderer(this, 39, 22);
        this.fredhead.setRotationPoint(0.0f, -13.0f, -0.5f);
        this.fredhead.addBox(-5.5f, -8.0f, -4.5f, 11.0f, 8.0f, 9.0f, 0.0f);
        this.armRightpad = new ModelRenderer(this, 70, 10);
        this.armRightpad.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.armRightpad.addBox(-2.5f, 0.0f, -2.5f, 5.0f, 9.0f, 5.0f, 0.0f);
        this.armRight2 = new ModelRenderer(this, 90, 20);
        this.armRight2.setRotationPoint(0.0f, 9.6f, 0.0f);
        this.armRight2.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 8.0f, 2.0f, 0.0f);
        this.setRotationAngle(this.armRight2, -0.17453292f, 0.0f, 0.0f);
        this.armRightpad2 = new ModelRenderer(this, 0, 26);
        this.armRightpad2.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.armRightpad2.addBox(-2.5f, 0.0f, -2.5f, 5.0f, 7.0f, 5.0f, 0.0f);
        this.handRight = new ModelRenderer(this, 20, 26);
        this.handRight.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.handRight.addBox(-2.0f, 0.0f, -2.5f, 4.0f, 4.0f, 5.0f, 0.0f);
        this.setRotationAngle(this.handRight, 0.0f, 0.0f, -0.05235988f);
        this.legRightpad = new ModelRenderer(this, 73, 33);
        this.legRightpad.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.legRightpad.addBox(-3.0f, 0.0f, -3.0f, 6.0f, 9.0f, 6.0f, 0.0f);
        this.legRight2 = new ModelRenderer(this, 20, 35);
        this.legRight2.setRotationPoint(0.0f, 9.6f, 0.0f);
        this.legRight2.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 8.0f, 2.0f, 0.0f);
        this.setRotationAngle(this.legRight2, (float)Math.PI / 90, 0.0f, 0.0f);
        this.legRightpad2 = new ModelRenderer(this, 0, 39);
        this.legRightpad2.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.legRightpad2.addBox(-2.5f, 0.0f, -3.0f, 5.0f, 7.0f, 6.0f, 0.0f);
        this.footRight = new ModelRenderer(this, 22, 39);
        this.footRight.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.footRight.addBox(-2.5f, 0.0f, -6.0f, 5.0f, 3.0f, 8.0f, 0.0f);
        this.setRotationAngle(this.footRight, (float)(-Math.PI) / 90, 0.0f, 0.0f);
        this.legLeftpad = new ModelRenderer(this, 48, 39);
        this.legLeftpad.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.legLeftpad.addBox(-3.0f, 0.0f, -3.0f, 6.0f, 9.0f, 6.0f, 0.0f);
        this.legLeft2 = new ModelRenderer(this, 72, 48);
        this.legLeft2.setRotationPoint(0.0f, 9.6f, 0.0f);
        this.legLeft2.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 8.0f, 2.0f, 0.0f);
        this.setRotationAngle(this.legLeft2, (float)Math.PI / 90, 0.0f, 0.0f);
        this.legLeftpad2 = new ModelRenderer(this, 16, 50);
        this.legLeftpad2.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.legLeftpad2.addBox(-2.5f, 0.0f, -3.0f, 5.0f, 7.0f, 6.0f, 0.0f);
        this.footLeft = new ModelRenderer(this, 72, 50);
        this.footLeft.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.footLeft.addBox(-2.5f, 0.0f, -6.0f, 5.0f, 3.0f, 8.0f, 0.0f);
        this.setRotationAngle(this.footLeft, (float)(-Math.PI) / 90, 0.0f, 0.0f);
        this.armLeftpad = new ModelRenderer(this, 38, 54);
        this.armLeftpad.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.armLeftpad.addBox(-2.5f, 0.0f, -2.5f, 5.0f, 9.0f, 5.0f, 0.0f);
        this.armLeft2 = new ModelRenderer(this, 90, 48);
        this.armLeft2.setRotationPoint(0.0f, 9.6f, 0.0f);
        this.armLeft2.addBox(-1.0f, 0.0f, -1.0f, 2.0f, 8.0f, 2.0f, 0.0f);
        this.setRotationAngle(this.armLeft2, -0.17453292f, 0.0f, 0.0f);
        this.armLeftpad2 = new ModelRenderer(this, 0, 58);
        this.armLeftpad2.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.armLeftpad2.addBox(-2.5f, 0.0f, -2.5f, 5.0f, 7.0f, 5.0f, 0.0f);
        this.handLeft = new ModelRenderer(this, 58, 56);
        this.handLeft.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.handLeft.addBox(-1.0f, 0.0f, -2.5f, 4.0f, 4.0f, 5.0f, 0.0f);
        this.setRotationAngle(this.handLeft, 0.0f, 0.0f, 0.05235988f);
        this.jaw = new ModelRenderer(this, 49, 65);
        this.jaw.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.jaw.addBox(-5.0f, 0.0f, -4.5f, 10.0f, 3.0f, 9.0f, 0.0f);
        this.setRotationAngle(this.jaw, 0.08726646f, 0.0f, 0.0f);
        this.frednose = new ModelRenderer(this, 17, 67);
        this.frednose.setRotationPoint(0.0f, -2.0f, -4.5f);
        this.frednose.addBox(-4.0f, -2.0f, -3.0f, 8.0f, 4.0f, 3.0f, 0.0f);
        this.earRight = new ModelRenderer(this, 8, 0);
        this.earRight.setRotationPoint(-4.5f, -5.5f, 0.0f);
        this.earRight.addBox(-1.0f, -3.0f, -0.5f, 2.0f, 3.0f, 1.0f, 0.0f);
        this.setRotationAngle(this.earRight, 0.05235988f, 0.0f, -1.0471976f);
        this.earLeft = new ModelRenderer(this, 40, 0);
        this.earLeft.setRotationPoint(4.5f, -5.5f, 0.0f);
        this.earLeft.addBox(-1.0f, -3.0f, -0.5f, 2.0f, 3.0f, 1.0f, 0.0f);
        this.setRotationAngle(this.earLeft, 0.05235988f, 0.0f, 1.0471976f);
        this.hat = new ModelRenderer(this, 70, 24);
        this.hat.setRotationPoint(0.0f, -8.4f, 0.0f);
        this.hat.addBox(-3.0f, -0.5f, -3.0f, 6.0f, 1.0f, 6.0f, 0.0f);
        this.setRotationAngle(this.hat, (float)(-Math.PI) / 180, 0.0f, 0.0f);
        this.earRightpad = new ModelRenderer(this, 85, 0);
        this.earRightpad.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.earRightpad.addBox(-2.0f, -5.0f, -1.0f, 4.0f, 4.0f, 2.0f, 0.0f);
        this.earRightpad_1 = new ModelRenderer(this, 40, 39);
        this.earRightpad_1.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.earRightpad_1.addBox(-2.0f, -5.0f, -1.0f, 4.0f, 4.0f, 2.0f, 0.0f);
        this.hat2 = new ModelRenderer(this, 78, 61);
        this.hat2.setRotationPoint(0.0f, 0.1f, 0.0f);
        this.hat2.addBox(-2.0f, -4.0f, -2.0f, 4.0f, 4.0f, 4.0f, 0.0f);
        this.setRotationAngle(this.hat2, (float)(-Math.PI) / 180, 0.0f, 0.0f);
        this.legRight2.addChild(this.footRight);
        this.fredhead.addChild(this.earRight);
        this.legLeft.addChild(this.legLeftpad);
        this.earLeft.addChild(this.earRightpad_1);
        this.fredbody.addChild(this.legLeft);
        this.armRight2.addChild(this.armRightpad2);
        this.armLeft2.addChild(this.handLeft);
        this.fredbody.addChild(this.armLeft);
        this.fredbody.addChild(this.legRight);
        this.armLeft.addChild(this.armLeft2);
        this.legRight.addChild(this.legRight2);
        this.armLeft2.addChild(this.armLeftpad2);
        this.legLeft.addChild(this.legLeft2);
        this.fredhead.addChild(this.hat);
        this.earRight.addChild(this.earRightpad);
        this.fredbody.addChild(this.crotch);
        this.fredbody.addChild(this.torso);
        this.armRight.addChild(this.armRight2);
        this.armRight2.addChild(this.handRight);
        this.fredbody.addChild(this.fredhead);
        this.legRight.addChild(this.legRightpad);
        this.fredhead.addChild(this.frednose);
        this.legLeft2.addChild(this.legLeftpad2);
        this.armRight.addChild(this.armRightpad);
        this.armLeft.addChild(this.armLeftpad);
        this.hat.addChild(this.hat2);
        this.legRight2.addChild(this.legRightpad2);
        this.fredhead.addChild(this.jaw);
        this.fredbody.addChild(this.armRight);
        this.legLeft2.addChild(this.footLeft);
        this.fredhead.addChild(this.earLeft);
        this.LeftArm = new ModelRenderer(this);
        this.LeftArm.setRotationPoint(5.0f, 2.0f, 0.0f);
        this.LeftArm.setTextureOffset(37, 37).addBox(-1.0f, -2.0f, -2.0f, 3.0f, 12.0f, 3.0f, 0.0f, false);
        this.textureWidth = 100;
        this.textureHeight = 80;
    }

    @Override
    public void setRotationAngles(T entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        super.setRotationAngles(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        this.currentEntity = entityIn;
        this.bipedLeftLegwear.copyModelAngles(this.bipedLeftLeg);
        this.bipedRightLegwear.copyModelAngles(this.bipedRightLeg);
        this.bipedLeftArmwear.copyModelAngles(this.bipedLeftArm);
        this.bipedRightArmwear.copyModelAngles(this.bipedRightArm);
        this.bipedBodyWear.copyModelAngles(this.bipedBody);
    }

    @Override
    public void render(MatrixStack matrixStackIn, IVertexBuilder bufferIn, int packedLightIn, int packedOverlayIn, float red, float green, float blue, float alpha) {
        boolean applyCustomModel = false;
        CustomModel customModel = Load.getInstance().getHooks().getModuleManagers().getCustomModel();
        if (customModel.isToggled()) {
            boolean others;
            ClientPlayerEntity client = Minecraft.getInstance().player;
            String currentName = ((Entity)this.currentEntity).getName().getString();
            boolean self = customModel.getElements().getSelected("Self") && ((Entity)this.currentEntity).getUniqueID().equals(client.getUniqueID());
            boolean friend = customModel.getElements().getSelected("Friends") && Load.getInstance().getHooks().getFriendManagers().is(currentName);
            boolean bl = others = customModel.getElements().getSelected("Others") && !Load.getInstance().getHooks().getFriendManagers().is(currentName) && !((Entity)this.currentEntity).getUniqueID().equals(client.getUniqueID());
            if (self || friend || others) {
                applyCustomModel = true;
            }
        }
        if (applyCustomModel && customModel.getMode().getSelected("Rabbit")) {
            matrixStackIn.push();
            GlStateManager.pushMatrix();
            GlStateManager.enableBlend();
            GlStateManager.blendFunc(770, 771);
            GlStateManager.color4f(1.0f, 1.0f, 1.0f, 1.0f);
            this.rabbitHead.rotateAngleX = this.bipedHead.rotateAngleX;
            this.rabbitHead.rotateAngleY = this.bipedHead.rotateAngleY;
            this.rabbitHead.rotateAngleZ = this.bipedHead.rotateAngleZ;
            this.rabbitLarm.rotateAngleX = this.bipedLeftArm.rotateAngleX;
            this.rabbitLarm.rotateAngleY = this.bipedLeftArm.rotateAngleY;
            this.rabbitLarm.rotateAngleZ = this.bipedLeftArm.rotateAngleZ;
            this.rabbitRarm.rotateAngleX = this.bipedRightArm.rotateAngleX;
            this.rabbitRarm.rotateAngleY = this.bipedRightArm.rotateAngleY;
            this.rabbitRarm.rotateAngleZ = this.bipedRightArm.rotateAngleZ;
            this.rabbitRleg.rotateAngleX = this.bipedRightLeg.rotateAngleX;
            this.rabbitRleg.rotateAngleY = this.bipedRightLeg.rotateAngleY;
            this.rabbitRleg.rotateAngleZ = this.bipedRightLeg.rotateAngleZ;
            this.rabbitLleg.rotateAngleX = this.bipedLeftLeg.rotateAngleX;
            this.rabbitLleg.rotateAngleY = this.bipedLeftLeg.rotateAngleY;
            this.rabbitLleg.rotateAngleZ = this.bipedLeftLeg.rotateAngleZ;
            this.rabbitBone.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            GlStateManager.disableBlend();
            GlStateManager.popMatrix();
            matrixStackIn.pop();
        } else if (applyCustomModel && customModel.getMode().getSelected("Jeff Killer")) {
            matrixStackIn.push();
            this.textureWidth = 64;
            this.textureHeight = 64;
            this.Head.rotateAngleX = this.bipedHead.rotateAngleX;
            this.Head.rotateAngleY = this.bipedHead.rotateAngleY;
            this.Head.rotateAngleZ = this.bipedHead.rotateAngleZ;
            this.LeftArm.rotateAngleX = this.bipedLeftArm.rotateAngleX;
            this.LeftArm.rotateAngleY = this.bipedLeftArm.rotateAngleY;
            this.LeftArm.rotateAngleZ = this.bipedLeftArm.rotateAngleZ;
            this.RightArm.rotateAngleX = -1.57f;
            this.RightArm.rotateAngleY = 0.0f;
            this.RightArm.rotateAngleZ = 0.0f;
            this.RightLeg.rotateAngleX = this.bipedRightLeg.rotateAngleX;
            this.RightLeg.rotateAngleY = this.bipedRightLeg.rotateAngleY;
            this.RightLeg.rotateAngleZ = this.bipedRightLeg.rotateAngleZ;
            this.LeftLeg.rotateAngleX = this.bipedLeftLeg.rotateAngleX;
            this.LeftLeg.rotateAngleY = this.bipedLeftLeg.rotateAngleY;
            this.LeftLeg.rotateAngleZ = this.bipedLeftLeg.rotateAngleZ;
            this.RightLeg.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.LeftLeg.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.Body.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.RightArm.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.Head.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.LeftArm.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.textureWidth = 100;
            this.textureHeight = 80;
            matrixStackIn.pop();
        } else if (applyCustomModel && customModel.getMode().getSelected("Chinchilla")) {
            matrixStackIn.push();
            matrixStackIn.scale(1.4f, 1.4f, 1.4f);
            matrixStackIn.translate(0.0, -0.45f, 0.0);
            this.Chin.rotateAngleY = this.chinHead.rotateAngleY;
            this.Chin.rotateAngleX = this.chinHead.rotateAngleX;
            this.chinHead.rotateAngleX = this.bipedHead.rotateAngleX;
            this.Nose.rotateAngleY = this.chinHead.rotateAngleY = this.bipedHead.rotateAngleY;
            this.Nose.rotateAngleX = this.chinHead.rotateAngleX;
            this.RightEar.rotateAngleY = this.chinHead.rotateAngleY + 2.094395f;
            this.LeftEar.rotateAngleY = this.chinHead.rotateAngleY + 1.047198f;
            this.LeftEye.rotateAngleY = this.chinHead.rotateAngleY - 1.047198f;
            this.RightEye.rotateAngleY = this.chinHead.rotateAngleY + 1.047198f;
            this.LeftFrontLeg.rotateAngleX = this.bipedLeftLeg.rotateAngleX;
            this.RightFrontLeg.rotateAngleX = this.bipedRightLeg.rotateAngleX;
            this.LeftFrontFoot.rotateAngleX = this.bipedLeftLeg.rotateAngleX;
            this.RightFrontFoot.rotateAngleX = this.bipedRightLeg.rotateAngleX;
            this.LeftRearFoot.rotateAngleX = -this.bipedLeftLeg.rotateAngleX;
            this.RightRearFoot.rotateAngleX = -this.bipedRightLeg.rotateAngleX;
            this.LeftWhiskers.rotateAngleY = this.chinHead.rotateAngleY - 0.1745329f;
            this.LeftWhiskers.rotateAngleX = this.chinHead.rotateAngleX - 0.1745329f;
            this.RightWhiskers.rotateAngleY = this.chinHead.rotateAngleY + 0.1745329f;
            this.RightWhiskers.rotateAngleX = this.chinHead.rotateAngleX + 0.1745329f;
            this.Back.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.Nose.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.RightEar.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.RightWhiskers.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.LeftEar.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.UpperTail.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.chinBody.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.LowerTail.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.RightRearFoot.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.LeftRearFoot.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.RightFrontLeg.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.RightFrontFoot.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.LeftFrontLeg.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.LeftFrontFoot.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.Chin.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.LeftWhiskers.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            this.chinHead.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
            matrixStackIn.pop();
        } else if (applyCustomModel && customModel.getMode().getSelected("Freddy Bear")) {
            matrixStackIn.push();
            this.fredhead.rotateAngleX = this.bipedHead.rotateAngleX;
            this.fredhead.rotateAngleY = this.bipedHead.rotateAngleY;
            this.fredhead.rotateAngleZ = this.bipedHead.rotateAngleZ;
            this.armLeft.rotateAngleX = this.bipedLeftArm.rotateAngleX;
            this.armLeft.rotateAngleY = this.bipedLeftArm.rotateAngleY;
            this.armLeft.rotateAngleZ = this.bipedLeftArm.rotateAngleZ;
            this.legRight.rotateAngleX = this.bipedRightLeg.rotateAngleX;
            this.legRight.rotateAngleY = this.bipedRightLeg.rotateAngleY;
            this.legRight.rotateAngleZ = this.bipedRightLeg.rotateAngleZ;
            this.legLeft.rotateAngleX = this.bipedLeftLeg.rotateAngleX;
            this.legLeft.rotateAngleY = this.bipedLeftLeg.rotateAngleY;
            this.legLeft.rotateAngleZ = this.bipedLeftLeg.rotateAngleZ;
            this.armRight.rotateAngleX = this.bipedRightArm.rotateAngleX;
            this.armRight.rotateAngleY = this.bipedRightArm.rotateAngleY;
            this.armRight.rotateAngleZ = this.bipedRightArm.rotateAngleZ;
            matrixStackIn.scale(0.75f, 0.65f, 0.75f);
            matrixStackIn.translate(0.0, 0.85f, 0.0);
            this.fredbody.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            matrixStackIn.pop();
        } else if (applyCustomModel && customModel.getMode().getSelected("White Demon")) {
            matrixStackIn.push();
            GlStateManager.pushMatrix();
            GlStateManager.enableBlend();
            GlStateManager.blendFunc(770, 771);
            GlStateManager.color4f(1.0f, 1.0f, 1.0f, 1.0f);
            this.head7.rotateAngleX = this.bipedHead.rotateAngleX;
            this.head7.rotateAngleY = this.bipedHead.rotateAngleY;
            this.head7.rotateAngleZ = this.bipedHead.rotateAngleZ;
            this.right_leg7.rotateAngleX = this.bipedRightLeg.rotateAngleX;
            this.right_leg7.rotateAngleY = this.bipedRightLeg.rotateAngleY;
            this.right_leg7.rotateAngleZ = this.bipedRightLeg.rotateAngleZ;
            this.left_leg7.rotateAngleX = this.bipedLeftLeg.rotateAngleX;
            this.left_leg7.rotateAngleY = this.bipedLeftLeg.rotateAngleY;
            this.left_leg7.rotateAngleZ = this.bipedLeftLeg.rotateAngleZ;
            this.left_arm7.rotateAngleX = this.bipedLeftArm.rotateAngleX;
            this.left_arm7.rotateAngleY = this.bipedLeftArm.rotateAngleY;
            this.left_arm7.rotateAngleZ = this.bipedLeftArm.rotateAngleZ;
            this.right_arm7.rotateAngleX = this.bipedRightArm.rotateAngleX;
            this.right_arm7.rotateAngleY = this.bipedRightArm.rotateAngleY;
            this.right_arm7.rotateAngleZ = this.bipedRightArm.rotateAngleZ;
            this.head7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_horn.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_horn.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.body7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_wing.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_wing.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_arm7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_arm7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_leg7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_leg7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            GlStateManager.disableBlend();
            GlStateManager.popMatrix();
            matrixStackIn.pop();
        } else if (applyCustomModel && customModel.getMode().getSelected("Demon")) {
            matrixStackIn.push();
            GlStateManager.pushMatrix();
            GlStateManager.enableBlend();
            GlStateManager.blendFunc(770, 771);
            GlStateManager.color4f(1.0f, 1.0f, 1.0f, 1.0f);
            this.head7.rotateAngleX = this.bipedHead.rotateAngleX;
            this.head7.rotateAngleY = this.bipedHead.rotateAngleY;
            this.head7.rotateAngleZ = this.bipedHead.rotateAngleZ;
            this.right_leg7.rotateAngleX = this.bipedRightLeg.rotateAngleX;
            this.right_leg7.rotateAngleY = this.bipedRightLeg.rotateAngleY;
            this.right_leg7.rotateAngleZ = this.bipedRightLeg.rotateAngleZ;
            this.left_leg7.rotateAngleX = this.bipedLeftLeg.rotateAngleX;
            this.left_leg7.rotateAngleY = this.bipedLeftLeg.rotateAngleY;
            this.left_leg7.rotateAngleZ = this.bipedLeftLeg.rotateAngleZ;
            this.left_arm7.rotateAngleX = this.bipedLeftArm.rotateAngleX;
            this.left_arm7.rotateAngleY = this.bipedLeftArm.rotateAngleY;
            this.left_arm7.rotateAngleZ = this.bipedLeftArm.rotateAngleZ;
            this.right_arm7.rotateAngleX = this.bipedRightArm.rotateAngleX;
            this.right_arm7.rotateAngleY = this.bipedRightArm.rotateAngleY;
            this.right_arm7.rotateAngleZ = this.bipedRightArm.rotateAngleZ;
            this.head7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_horn.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_horn.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.body7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_wing.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_wing.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_arm7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_arm7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.left_leg7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            this.right_leg7.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
            GlStateManager.disableBlend();
            GlStateManager.popMatrix();
            matrixStackIn.pop();
        } else {
            super.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        }
    }

    public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }

    @Override
    protected Iterable<ModelRenderer> getBodyParts() {
        return Iterables.concat(super.getBodyParts(), ImmutableList.of(this.bipedLeftLegwear, this.bipedRightLegwear, this.bipedLeftArmwear, this.bipedRightArmwear, this.bipedBodyWear));
    }

    public ModelRenderer getRandomModelRenderer(Random randomIn) {
        return this.modelRenderers != null && !this.modelRenderers.isEmpty() ? this.modelRenderers.get(randomIn.nextInt(this.modelRenderers.size())) : this.bipedBody;
    }

    public void renderEars(MatrixStack matrixStackIn, IVertexBuilder bufferIn, int packedLightIn, int packedOverlayIn) {
        this.bipedDeadmau5Head.copyModelAngles(this.bipedHead);
        this.bipedDeadmau5Head.rotationPointX = 0.0f;
        this.bipedDeadmau5Head.rotationPointY = 0.0f;
        this.bipedDeadmau5Head.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
    }

    public void renderCape(MatrixStack matrixStackIn, IVertexBuilder bufferIn, int packedLightIn, int packedOverlayIn) {
        this.bipedCape.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
    }

    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        this.bipedLeftArmwear.showModel = visible;
        this.bipedRightArmwear.showModel = visible;
        this.bipedLeftLegwear.showModel = visible;
        this.bipedRightLegwear.showModel = visible;
        this.bipedBodyWear.showModel = visible;
        this.bipedCape.showModel = visible;
        this.bipedDeadmau5Head.showModel = visible;
        if (this.rabbitBone != null) {
            this.rabbitBone.showModel = visible;
            this.rabbitHead.showModel = visible;
            this.rabbitLarm.showModel = visible;
            this.rabbitRarm.showModel = visible;
            this.rabbitLleg.showModel = visible;
            this.rabbitRleg.showModel = visible;
        }
        if (this.head7 != null) {
            this.head7.showModel = visible;
            this.left_horn.showModel = visible;
            this.right_horn.showModel = visible;
            this.body7.showModel = visible;
            this.left_wing.showModel = visible;
            this.right_wing.showModel = visible;
            this.left_arm7.showModel = visible;
            this.right_arm7.showModel = visible;
            this.left_leg7.showModel = visible;
            this.right_leg7.showModel = visible;
        }
    }

    @Override
    public void translateHand(HandSide sideIn, MatrixStack matrixStackIn) {
        ModelRenderer modelrenderer = this.getArmForSide(sideIn);
        if (this.smallArms) {
            float f = 0.5f * (float)(sideIn == HandSide.RIGHT ? 1 : -1);
            modelrenderer.rotationPointX += f;
            modelrenderer.translateRotate(matrixStackIn);
            modelrenderer.rotationPointX -= f;
        } else {
            modelrenderer.translateRotate(matrixStackIn);
        }
    }
}
